# don't edit, generated by vsdk_adas.sh script
require recipes-demos/common-demos.inc

EXTERNALSRC_BUILD := "${EXTERNALSRC}/demos/apps/isp_stereo_apexbm/build-v234ce-gnu-linux-d"
DEPENDS += "ocv"
DEPENDS += "ffmpeg"
