# don't edit, generated by vsdk_adas.sh script
require recipes-demos/common-demos.inc

EXTERNALSRC_BUILD := "${EXTERNALSRC}/demos/apps/apex_isp_face_detection_cv/build-v234ce-gnu-linux-d"
DEPENDS += "ffmpeg"
