# don't edit, generated by vsdk_adas.sh script
require recipes-demos/common-demos.inc
inherit insane

EXTERNALSRC_BUILD := "${EXTERNALSRC}/demos/isp/isp_ov10635_viu_s/build-v234ce-gnu-linux-d"
DEPENDS += "ocv"
INSANE_SKIP_${PN} += "build-deps"
